spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/reserve_db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

    jpa:
      hibernate:
        ddl-auto: update
        naming:
          physical-strategy:
          org:
            hibernate:
              boot:
                model:
                  naming:
                    PhysicalNamingStrategyStandardImpl
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true

    flyway:
      url: jdbc:postgresql://localhost:5432/reserve_db
      user: admin
      password: admin
      locations: classpath:db/migration

  application:
    name: reserve